Keep other 3th party repos enabled as much as possible
stephdl/nethserver-urbackup pull request #1
Opened 2021-08-07 14:37 UTC by markVnl

- Omit running signal-event software-repos-save explicitly

Hi Stephane, do not know if this is released or  simply is being forgotten...

**NOTE** : review this (for all other nethserverians i did rebuild and test, 
I think you know this better than me, so keep the review to you :)

2021-08-11 14:35 UTC, stephdl requested changes

2021-08-11 14:35 UTC, stephdl commented on createlinks
>               'initialize-default-databases' => '00',
please remove the comma at the end

2021-08-11 14:35 UTC, stephdl commented on createlinks
> +    templates2events("/etc/nethserver/eorepo.conf", $event);
`/etc/nethserver/eorepo.conf` can we only set this template to nethserver-urbackup-update (only for update and first install)

2021-08-11 17:06 UTC, markVnl commented on createlinks
> +    templates2events("/etc/nethserver/eorepo.conf", $event);
Yes do you prefer to split op the foreach ?

```
my $event = "nethserver-urbackup-update";
event_actions($event,
     'initialize-default-databases' => '00')

templates2events("/etc/httpd/conf.d/default-virtualhost.inc",  $event);
templates2events("/etc/httpd/conf.d/urbackup.conf",  $event);
templates2events("/etc/nethserver/eorepo.conf", $event);
event_services($event, 'httpd' => 'reload');
event_services($event, 'urbackup-server' => 'restart');

my $event = "nethserver-urbackup-save";
event_actions($event,
    'firewall-adjust' => '10');

templates2events("/etc/httpd/conf.d/default-virtualhost.inc",  $event);
templates2events("/etc/httpd/conf.d/urbackup.conf",  $event);

event_services($event, 'httpd' => 'reload');
event_services($event, 'urbackup-server' => 'restart');
```

2021-08-11 17:44 UTC, markVnl commented on createlinks
> +    templates2events("/etc/nethserver/eorepo.conf", $event);
Or keep as is, like i did now?

2021-08-12 12:25 UTC, stephdl commented on createlinks
> +    templates2events("/etc/nethserver/eorepo.conf", $event);
good

2021-08-12 12:25 UTC, stephdl approved these changes

2021-08-12 12:26 UTC, merged

2021-08-12 12:31 UTC, stephdl commented
released @markVnl